version: '3'
services: 

  app:
    build:
      context: .
      args:
        NODE_BASE: ${NODE_BASE}
    depends_on: 
      - postgres
    volumes:
      - "${PWD}/src/discord.config.json:/app/src/discord.config.json"
    container_name: dicebot

  postgres:
    restart: always
    image: ${POSTGRES_BASE}
    ports: 
      - "5432:5432"
    volumes: 
      - "${PWD}/db-data:/var/lib/postgresql/data"
    environment: 
      - POSTGRES_PASSWORD=alpine
      - POSTGRES_DB=dicebot
    container_name: postgres
    
